services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./airbnb:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"
    networks:
      - default
volumes:
  node_modules:
